<a href="https://colab.research.google.com/github/MonikaLamba/LBSIM_SUPERVISED_LEARNING/blob/main/Supervised_Learning_part_2_diabetic_null.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import library - numpy and pandas

In [27]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/diabetes_null_values.csv') #deatil about how you have uplaod data

In [28]:
df # reading data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0

In [29]:
df.head() # shows top 5 rows

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1

In [30]:
df.head(2) # top 2 rows of the data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0

In [31]:
df.shape   # Size of the dataset

(768, 9)

In [32]:
df.describe() # description of the dataset - count, mean, standard deviation, mininum and maximum vale (column wise), percentile percentage

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,767.000000,766.000000,765.000000,763.000000,762.000000,765.000000,767.000000,768.000000
mean,3.845052,120.908735,69.063969,20.549020,80.272608,32.001969,0.472139,33.241199,0.348958
std,3.369578,31.991056,19.362313,15.963039,115.465936,7.894103,0.331852,11.767902,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,36.000000,32.000000,0.374000,29.000000,0.000000
75%,6.000000,140.500000,80.000000,32.000000,128.500000,36.575000,0.627000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [33]:
df.tail() # 5 rows from last rows

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0

In [34]:
df.tail(7) # last 7 rows from the data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
761,9,170.0,74.0,31.0,0.0,44.0,0.403,43.0,1
762,9,89.0,62.0,0.0,0.0,22.5,0.142,33.0,0
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0

In [35]:
df.head(6) # last 6 rows from the dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1
5,5,116.0,74.0,0.0,0.0,25.6,0.201,30.0,0

In [36]:
df.isna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

In [37]:
df.isna().sum()

Pregnancies                 0
Glucose                     1
BloodPressure               2
SkinThickness               3
Insulin                     5
BMI                         6
DiabetesPedigreeFunction    3
Age                         1
Outcome                     0
dtype: int64

In [38]:
display(df.isna().sum().sort_values(ascending=False))  # checking isnull/isna values in data (column wise) and make sum and sort

BMI                         6
Insulin                     5
DiabetesPedigreeFunction    3
SkinThickness               3
BloodPressure               2
Age                         1
Glucose                     1
Pregnancies                 0
Outcome                     0
dtype: int64